=== XXnikoDarkXX/Lenguajes2-Trimestre/XML+XSD+CSS/repasoValidador.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <xs:element name="GENTE">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="PERSONA"  minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
        <xs:sequence>
        <xs:element name="APELLIDO" type="xs:string" minOccurs="1" maxOccurs="1"/>
        <xs:element name="NOMBRE" type="xs:string"minOccurs="1" maxOccurs="1"/>
        <xs:element name="APODO" type="xs:string" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
        </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== XXnikoDarkXX/Lenguajes2-Trimestre/XML+XSD+CSS/repasoxml.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="repasoEstilos.css"?>
<GENTE xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///F:/1%C2%BADAM/LENGUAJEDEMARCAS/2%C2%BATrimestre/xml/repasoValidador.xsd">

<PERSONA>
<APELLIDO>Un apellido</APELLIDO>
<NOMBRE>Un nombre</NOMBRE>
<APODO>Un apodo</APODO>
</PERSONA>
<PERSONA>
<APELLIDO>Otro apellido</APELLIDO>
<NOMBRE>Otro nombre</NOMBRE>
<APODO></APODO>
</PERSONA>
</GENTE>
