=== XXnikoDarkXX/Lenguajes2-Trimestre/Lenguaje3ºTriemstre/XML/esquemaPez.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="acuario">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="pez" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="nombre"/>
              <xs:element type="xs:string" name="edad"/>
              <xs:element type="xs:string" name="color" maxOccurs="2" minOccurs="1"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== XXnikoDarkXX/Lenguajes2-Trimestre/Lenguaje3ºTriemstre/XML/fichaPez.xml
<?xml version="1.0" encoding="UTF-8"?>
<acuario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/nicoc/Desktop/XML/esquemaPez.xsd">
<pez>
<nombre>Pingi</nombre>
<edad>1 año</edad>
<color>Rojo</color>
<color>Verde</color>
</pez>


<pez>
<nombre>faz</nombre>
<edad>3 año</edad>
<color>Azul</color>
</pez>

</acuario>

=== XXnikoDarkXX/Lenguajes2-Trimestre/Lenguaje3ºTriemstre/JavasCript yContactoTerminado/xml/fichaPez.xml
<?xml version="1.0" encoding="UTF-8"?>
<acuario xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///C:/Users/nicoc/Desktop/XML/esquemaPez.xsd">
<pez>
<nombre>Pingi</nombre>
<edad>1 Año</edad>
<color>Rojo</color>
<color>Verde</color>
</pez>


<pez>
<nombre>Faz</nombre>
<edad>3 Año</edad>
<color>Azul</color>
</pez>


<pez>
<nombre>Nemo</nombre>
<edad>2 Año</edad>
<color>Naranja</color>
</pez>


</acuario>
